# Create network : docker network create nginx-proxy-net
version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:${NGINX_PROXY_VER}
    container_name: ${NGINX_PROXY_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-proxy-net
    volumes:
      - ${NGINX_DATA_FOLDER}/conf.d:/etc/nginx/conf.d
      - ${NGINX_DATA_FOLDER}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_DATA_FOLDER}/html:/usr/share/nginx/html
      - ${NGINX_DATA_FOLDER}/htpasswd:/etc/nginx/htpasswd:ro
      - ${NGINX_DATA_FOLDER}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
        - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
##################################################################

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:${NGINX_COMPANION_VER}
    container_name: ${NGINX_COMPANION_CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - nginx-proxy-net
    depends_on:
      - ${NGINX_PROXY_CONTAINER_NAME}
    volumes:
      - ${NGINX_DATA_FOLDER}/certs:/etc/nginx/certs 
      - ${NGINX_DATA_FOLDER}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_DATA_FOLDER}/html:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro       
##################################################################

networks:
  nginx-proxy-net:
    external: true
